services:
  server1:
    build:
        context: ./server
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - CONSUMER_GROUP_ID=chat2
    depends_on:
      elastic:
        condition: service_healthy
  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONSUMER_GROUP_ID=chat1
    depends_on:
      elastic:
        condition: service_healthy

  elastic:
    image: elastic/elasticsearch:7.17.25
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50


  broker:
    image: apache/kafka:3.9.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2