services:
  backend:
    build:
        context: ./server
        dockerfile: Dockerfile
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      elastic:
        condition: service_healthy
    deploy:
      replicas: 3
    restart: always

  history:
    build:
      context: ./historyService
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      elastic:
        condition: service_healthy
    deploy:
      replicas: 3
    restart: always

  llm:
    build:
        context: ./llm
        dockerfile: Dockerfile
    ports:
      - "5000:5000"

  llm1:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  llm2:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

  elastic:
    image: elastic/elasticsearch:7.17.25
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  broker:
    image: apache/kafka:3.9.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # So viel Konfiguration, um KRaft zu aktivieren, da Zookeeper für Kafka deprecated ist
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093

  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    deploy:
      replicas: 1
